# Generated by Django 5.2.8 on 2025-11-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Short symbol of the coin, e.g. BTC, ETH.', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Full name of the coin, e.g. Bitcoin.', max_length=50)),
            ],
        ),
    ]
